output_folder: 'C:\Users\celine.gross\Social Finance Ltd\CS Front Door Data Collaboration - Documents\06. Sensitive data (restricted)\West Berkshire\test_code'

merged_annex-a_filename: "{output_folder}/annex-a-merged.xlsx"
error_report_filename: "{output_folder}/annex-a-error-report.xlsx"
column_report_filename: "{output_folder}/annex-a-column-report.xlsx"

cleaned_annex-a_filename: "{output_folder}/annex-a-cleaned.xlsx"
matching_report_filename: "{output_folder}/matching-report.xlsx"

input_files:

    - root: 'C:\Users\celine.gross\Social Finance Ltd\CS Front Door Data Collaboration - Documents\06. Sensitive data (restricted)\West Berkshire\input\annex_a'
      include: "**/*.xlsx"



