ChildIdentifiers:
    LAchildID:
        maxlength: 10
        type: alphanumeric
    UPN:
        length: 13
        regex:
            - /[A-Z]\d{10}/i
            - /[A-Z]\d{9}[A-Z]/i
    FormerUPN:
        length: 13
        regex:
            - /[A-Z]\d{10}/i
            - /[A-Z]\d{9}[A-Z]/i
    UPNunknown:
        category:
        - code: UN1
        - code: UN2
        - code: UN3
        - code: UN4
        - code: UN5
        - code: UN6
        - code: UN7
    PersonBirthDate:
        canbeblank: yes
        date: "%Y-%m-%d"
    ExpectedPersonBirthDate:
        date: "%Y-%m-%d"
    GenderCurrent:
        category:
        - code: "1"
          name: Male
        - code: "2"
          name: Female
        - code: "0"
          name: Not recorded
        - code: "9"
          name: Indeterminate
    PersonDeathDate:
        date: "%Y-%m-%d"

ChildCharacteristics:
    Ethnicity:
        category:
        - code: WBRI
          name: White British
        - code: WIRI
          name: White Irish
        - code: WIRT
          name: Traveller of Irish heritage
        - code: WOTH
          name: Any other White background
        - code: WROM
          name: Gypsy/Roma
        - code: MWBC
          name: White and Black Caribbean
        - code: MWBA
          name: White and Black African
        - code: MWAS
          name: White and Asian
        - code: MOTH
          name: Any other mixed background
        - code: AIND
          name: Indian
        - code: APKN
          name: Pakistani
        - code: ABAN
          name: Bangladeshi
        - code: AOTH
          name: Any other Asian background
        - code: BCRB
          name: Caribbean
        - code: BAFR
          name: African
        - code: BOTH
          name: Any other black background
        - code: CHNE
          name: Chinese
        - code: OOTH
          name: Any other ethnic group
        - code: REFU
          name: Refused
        - code: NOBT
          name: Information not yet obtained
    Disabilities:
        Disability: 
            category:
            - code: NONE
              name: No disability
            - code: MOB
              name: Mobility
            - code: HAND
              name: Hand function
            - code: PC
              name: Personal care
            - code: INC
              name: Incontinence
            - code: COMM
              name: Communication
            - code: LD
              name: Learning
            - code: HEAR
              name: Hearing
            - code: VIS
              name: Vision
            - code: BEH
              name: Behaviour
            - code: CON
              name: Consciousness
            - code: AUT
              name: Autism
            - code: DDA
              name: Other
CINdetails:
    CINreferralDate:
        date: "%Y-%m-%d"
    ReferralSource:
        category:
            - code: '1A'
              name: INDIVIDUAL – family member, relative or carer
            - code: '1B'
              name: INDIVIDUAL – acquaintance (including neighbours and child minders)
            - code: '1C'
              name: INDIVIDUAL – self
            - code: '1D'
              name: INDIVIDUAL – other (including strangers)
            - code: '2A'
              name: SCHOOLS
            - code: '2B'
              name: EDUCATION SERVICES
            - code: '3A'
              name: HEALTH SERVICES – general practitioner (GP)
            - code: '3B'
              name: HEALTH SERVICES – health visitor
            - code: '3C' 
              name: HEALTH SERVICES – school nurse
            - code: '3D'
              name: HEALTH SERVICES – other primary health services
            - code: '3E'
              name: HEALTH SERVICES – A&E (accident and emergency department)
            - code: '3F'
              name: HEALTH SERVICES – other (for example hospice) 
            - code: '4' 
              name: HOUSING - local authority housing or housing association
            - code: '5A' 
              name: LA SERVICES – social care for example adults social care services  
            - code: '5B'
              name: LA SERVICES – other internal (department other than social care in local authorities, for example, youth offending (excluding housing))
            - code: '5C'
              name: LA SERVICES – external, for example, from another local authority’s adults social care services
            - code: '6'
              name: POLICE
            - code: '7'
              name: OTHER LEGAL AGENCY – including courts, probation, immigration, CAFCASS (Children and Family Court Advisory and Support Service) or prison
            - code: '8'
              name: OTHER – including children’s centres, independent agency providers or voluntary organisations
            - code: '9'
              name: ANONYMOUS
            - code: '10'
              name: UNKNOWN
    PrimaryNeedCode:
        category:
            - code: N1
              name: Abuse or neglect
            - code: N2
              name: "Child's disability"
            - code: N3
              name: Parental disability or illness
            - code: N4
              name: Family in acute stress
            - code: N5
              name: Family dysfunction
            - code: N6
              name: Socially unacceptable behaviour
            - code: N7
              name: Low income
            - code: N8
              name: Absent parenting
            - code: N9
              name: Cases other than children in need
            - code: N0
              name: Not stated
    CINclosureDate:
        date: "%Y-%m-%d"
    ReasonForClosure:
        category:
            - code: RC1
              name: Adopted
            - code: RC2
              name: Died
            - code: RC3
              name: Child arrangements order
            - code: RC4
              name: Special guardianship order
            - code: RC5
              name: Transferred to services of another local authority
            - code: RC6
              name: Transferred to adult social care services
            - code: RC7
              name: Services ceased for any other reason, including child no longer in need
            - code: RC8
              name: Case closed after assessment, no further action
    ReferralNFA:
        category:
            - code: "1"
              name: "True"
            - code: "0"
              name: "False"
    DateOfInitialCPC:
        date: "%Y-%m-%d"
    Assessments:
        AssessmentActualStartDate:
            date: "%Y-%m-%d"
        AssessmentInternalReviewDate:
            canbeblank: yes
            date: "%Y-%m-%d"
        AssessmentAuthorisationDate:
            date: "%Y-%m-%d"
        FactorsIdentifiedAtAssessment:
            AssessmentFactors:
                category:
                    - code: 1A
                      name: "Alcohol misuse: concerns about alcohol misuse by the child"
                    - code: 1B
                      name: "Alcohol misuse: concerns about alcohol misuse by the parent(s)/carer(s)"
                    - code: 1C
                      name: "Alcohol misuse: concerns about alcohol misuse by another person living in the household"
                    - code: 2A
                      name: "Drug misuse: concerns about drug misuse by the child"
                    - code: 2B
                      name: "Drug misuse: concerns about drug misuse by the parent(s)/carer(s)"
                    - code: 2C
                      name: "Drug misuse: concerns about drug misuse by another person living in the household"
                    - code: 3A
                      name: "Domestic violence: concerns about the child being the subject of domestic violence"
                    - code: 3B
                      name: "Domestic violence: concerns about the child’s parent(s)/carer(s) being the subject of domestic violence"
                    - code: 3C
                      name: "Domestic violence: concerns about another person living in the household being the subject of domestic violence"
                    - code: 4A
                      name: "Mental health: concerns about the mental health of the child"
                    - code: 4B
                      name: "Mental health: concerns about the mental health of the parent(s)/carer(s)"
                    - code: 4C
                      name: "Mental health: concerns about the mental health of another person in the family/household"
                    - code: 5A
                      name: "Learning disability: concerns about the child’s learning disability"
                    - code: 5B
                      name: "Learning disability: concerns about the parent(s)/carer(s) learning disability"
                    - code: 5C
                      name: "Learning disability: concerns about another person in the family/household’s learning disability"
                    - code: 6A
                      name: "Physical disability or illness: concerns about a physical disability or illness of the child"
                    - code: 6B
                      name: "Physical disability or illness: concerns about a physical disability or illness of the parent(s)/carer(s)"
                    - code: 6C
                      name: "Physical disability or illness: concerns about a physical disability or illness of another person in the family/household"
                    - code: 7A
                      name: "Young carer: concerns that services may be required or the child’s health or development may be impaired due to their caring responsibilities"
                    - code: 8B
                      name: "Privately fostered: concerns that services may be required or the child may be at risk as a privately fostered child - overseas children who intend to return"
                    - code: 8C
                      name: "Privately fostered: concerns that services may be required or the child may be at risk as a privately fostered child - overseas children who intend to stay"
                    - code: 8D
                      name: "Privately fostered: concerns that services may be required or the child may be at risk as a privately fostered child - UK children in educational placements"
                    - code: 8E
                      name: "Privately fostered: concerns that services may be required or the child may be at risk as a privately fostered child - UK children making alternative family arrangements"
                    - code: 8F
                      name: "Privately fostered: concerns that services may be required or the child may be at risk as a privately fostered child - other"
                    - code: 9A
                      name: "UASC: concerns that services may be required or the child may be at risk of harm as an unaccompanied asylum-seeking child"
                    - code: 10A
                      name: "Missing: concerns that services may be required or the child may be at risk of harm due to going/being missing"
                    - code: 11A
                      name: "Child sexual exploitation: concerns that services may be required or the child may be at risk of harm due to child sexual exploitation"
                    - code: 12A
                      name: "Trafficking: concerns that services may be required or the child may be at risk of harm due to trafficking"
                    - code: 13A
                      name: "Gangs: concerns that services may be required or the child may be at risk of harm because of involvement in/with gangs"
                    - code: 14A
                      name: "Socially unacceptable behaviour: concerns that services may be required or the child may be at risk due to their socially unacceptable behaviour"
                    - code: 15A
                      name: "Self-harm: concerns that services may be required or due to suspected/actual self-harming child may be at risk of harm"
                    - code: 16A
                      name: "Abuse or neglect – ‘NEGLECT’: concerns that services may be required or the child may be suffering or likely to suffer significant harm due to abuse or neglect"
                    - code: 17A
                      name: "Abuse or neglect – ‘EMOTIONAL ABUSE’: concerns that services may be required or the child may be suffering or likely to suffer significant harm due to abuse or neglect"
                    - code: 18A
                      name: "Abuse or neglect – ‘PHYSICAL ABUSE’: concerns that services may be required or the child may be suffering or likely to suffer significant harm due to abuse or neglect"
                    - code: 19A
                      name: "Abuse or neglect – ‘SEXUAL ABUSE’: concerns that services may be required or the child may be suffering or likely to suffer significant harm due to abuse or neglect"
                    - code: "20"
                      name: "Other"
                    - code: "21"
                      name: "No factors identified - only use this if there is no evidence of any of the factors above and no further action is being taken"
                    - code: 22A
                      name: "Female genital mutilation (FGM) - concerns that services may be required or the child may be at risk due to female genital mutilation"
                    - code: 23A
                      name: "Abuse linked to faith or belief - concerns that services may be required or the child may be at risk due to abuse linked to faith or belief"
    Section47:
        S47ActualStartDate:
            date: "%Y-%m-%d"
        InitialCPCtarget:
            canbeblank: yes
            date: "%Y-%m-%d"
        DateOfInitialCPC:
            date: "%Y-%m-%d"
        ICPCnotRequired:
            category:
                - code: "1"
                  name: "True"
                - code: "0"
                  name: "False"
    ChildProtectionPlans:
        CPPstartDate:
            date: "%Y-%m-%d"
        InitialCategoryOfAbuse:
            category:
                - code: NEG
                  name: Neglect
                - code: PHY
                  name: Physical abuse
                - code: SAB
                  name: Sexual abuse
                - code: EMO
                  name: Emotional abuse
                - code: MUL
                  name: Multiple/not recommended
        LatestCategoryOfAbuse:
            category:
                - code: NEG
                  name: Neglect
                - code: PHY
                  name: Physical abuse
                - code: SAB
                  name: Sexual abuse
                - code: EMO
                  name: Emotional abuse
                - code: MUL
                  name: Multiple/not recommended
        NumberOfPreviousCPP: integer
        CPPendDate:
            date: "%Y-%m-%d"
        Reviews:
            CPPreviewDate:
                date: "%Y-%m-%d"

